export const categoriasStites: string[] = [
	'Productividad',
	'Social',
	'Comunicación',
	'UX',
	'Redes',
	'Entretenimiento',
	'Musica y Audio',
	'TV',
	'Peliculas',
	'Documentation',
	'Browser',
	'CMS',
	'Inspiration',
	'Illustraciones',
	'Icons',
	'Mochups + Kits',
	'Typography',
	'Stock Photos',
	'Learning',
	'Blogs',
	'Podscasts',
	'Books',
	'Accessibility',
	'Community',
	'Design Tools',
	'UX Tools',
	'Color Tools',
	'Proyect Tools',
	'AI Tools',
	'Website Builder',
	'Community',
	'Education',
	'Software'
];
